import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { cliApi } from '../api.js';

interface InitAnswers {
  workspaceName: string;
  adminEmail: string;
  adminPassword: string;
  confirmPassword: string;
  generateEncryptionKey: boolean;
  dataDir: string;
}

export interface InitOptions {
  yes?: boolean;
  email?: string;
  password?: string;
  workspace?: string;
  dataDir?: string;
}

/**
 * First-time setup wizard for HonorClaw.
 *
 * - Generates encryption keys
 * - Creates the admin user
 * - Writes the configuration file
 *
 * Supports non-interactive mode via --yes flag.
 */
export async function runInit(opts?: InitOptions): Promise<void> {
  console.log(chalk.bold('\nHonorClaw Setup Wizard\n'));

  const nonInteractive = opts?.yes ?? false;

  // Check if already initialized
  const configPath = path.resolve('honorclaw.yaml');
  if (fs.existsSync(configPath)) {
    if (nonInteractive) {
      console.log(chalk.yellow('honorclaw.yaml already exists. Overwriting (--yes mode).'));
    } else {
      const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([
        {
          type: 'confirm',
          name: 'overwrite',
          message: 'honorclaw.yaml already exists. Overwrite?',
          default: false,
        },
      ]);
      if (!overwrite) {
        console.log(chalk.dim('Aborted.'));
        return;
      }
    }
  }

  let answers: InitAnswers;

  if (nonInteractive) {
    // Non-interactive mode: use CLI flags or defaults
    const adminEmail = opts?.email ?? 'admin@honorclaw.local';
    const adminPassword = opts?.password ?? crypto.randomBytes(16).toString('base64url');

    if (!opts?.password) {
      console.log(chalk.yellow(`Generated admin password: ${adminPassword}`));
      console.log(chalk.dim('(Save this — it will not be shown again)\n'));
    }

    answers = {
      workspaceName: opts?.workspace ?? 'default',
      adminEmail,
      adminPassword,
      confirmPassword: adminPassword,
      generateEncryptionKey: true,
      dataDir: opts?.dataDir ?? '/data/honorclaw',
    };
  } else {
    // Interactive mode
    answers = await inquirer.prompt<InitAnswers>([
      {
        type: 'input',
        name: 'workspaceName',
        message: 'Workspace name:',
        default: 'default',
        validate: (v: string) => v.trim().length > 0 || 'Workspace name is required',
      },
      {
        type: 'input',
        name: 'adminEmail',
        message: 'Admin email:',
        validate: (v: string) => v.includes('@') || 'Enter a valid email address',
      },
      {
        type: 'password',
        name: 'adminPassword',
        message: 'Admin password:',
        mask: '*',
        validate: (v: string) => v.length >= 12 || 'Password must be at least 12 characters',
      },
      {
        type: 'password',
        name: 'confirmPassword',
        message: 'Confirm password:',
        mask: '*',
        validate: (v: string, a?: InitAnswers) =>
          v === a?.adminPassword || 'Passwords do not match',
      },
      {
        type: 'confirm',
        name: 'generateEncryptionKey',
        message: 'Generate a new encryption key?',
        default: true,
      },
      {
        type: 'input',
        name: 'dataDir',
        message: 'Data directory:',
        default: '/data/honorclaw',
      },
    ]);
  }

  // ── Generate encryption key ─────────────────────────────────────────
  let encryptionKey: string;
  if (answers.generateEncryptionKey) {
    encryptionKey = crypto.randomBytes(32).toString('base64');
    console.log(chalk.green('Encryption key generated.'));
    if (!nonInteractive) {
      console.log(chalk.dim('Store this securely — it cannot be recovered:\n'));
      console.log(`  ${chalk.yellow(encryptionKey)}\n`);
    }
  } else {
    const { key } = await inquirer.prompt<{ key: string }>([
      {
        type: 'password',
        name: 'key',
        message: 'Encryption key (base64-encoded 32 bytes):',
        mask: '*',
        validate: (v: string) => {
          try {
            return Buffer.from(v, 'base64').length === 32 || 'Must be a base64-encoded 32-byte key';
          } catch {
            return 'Must be a valid base64-encoded 32-byte key';
          }
        },
      },
    ]);
    encryptionKey = key;
  }

  // ── Generate session cookie secret ──────────────────────────────────
  const cookieSecret = crypto.randomBytes(32).toString('base64url');

  // ── Generate JWT signing key ────────────────────────────────────────
  const jwtSecret = crypto.randomBytes(48).toString('base64url');

  // ── Write config file ───────────────────────────────────────────────
  const config = [
    '# HonorClaw Configuration',
    '# Generated by `honorclaw init`',
    '',
    'server:',
    '  port: 3000',
    '  host: "0.0.0.0"',
    '  corsOrigins:',
    '    - "http://localhost:3000"',
    `  sessionCookieSecret: "${cookieSecret}"`,
    '',
    'database:',
    '  # Use socket for embedded Docker deployment, or url for external databases',
    '  # socket: /var/run/postgresql',
    '  # url: postgresql://honorclaw:password@localhost:5432/honorclaw',
    '  name: honorclaw',
    '  poolSize: 10',
    '',
    'redis:',
    '  # Use socket for embedded Docker deployment, or url for external Redis',
    '  # socket: /var/run/redis/redis.sock',
    '  # url: redis://localhost:6379',
    '',
    'auth:',
    '  jwtIssuer: honorclaw',
    '  accessTokenTtlMinutes: 60',
    '  refreshTokenTtlDays: 7',
    '  mfaRequired: false',
    '',
    'llm:',
    '  defaultModel: "ollama/llama3.2"',
    '  providers: {}',
    '',
    'embeddings:',
    '  provider: ollama',
    '  model: nomic-embed-text',
    '',
    'security:',
    '  mode: namespace',
    '',
    'storage:',
    '  type: local',
    `  root: "${answers.dataDir}"`,
    '',
    'tools:',
    '  timeoutSeconds: 30',
    '  registries:',
    '    - type: local',
    '',
  ].join('\n');

  fs.writeFileSync(configPath, config, 'utf-8');
  console.log(chalk.green(`Configuration written to ${configPath}`));

  // ── Store secrets in .env file (gitignored) ─────────────────────────
  const envPath = path.resolve('.env');
  const postgresPassword = crypto.randomBytes(24).toString('base64url');
  const redisPassword = crypto.randomBytes(24).toString('base64url');
  const envContent = [
    '# HonorClaw secrets — DO NOT COMMIT',
    `HONORCLAW_MASTER_KEY=${encryptionKey}`,
    `JWT_SECRET=${jwtSecret}`,
    `SESSION_COOKIE_SECRET=${cookieSecret}`,
    `POSTGRES_PASSWORD=${postgresPassword}`,
    `REDIS_PASSWORD=${redisPassword}`,
    '',
  ].join('\n');

  fs.writeFileSync(envPath, envContent, { mode: 0o600 });
  console.log(chalk.green(`Secrets written to ${envPath}`));

  // ── Create admin user via API (if server is running) ────────────────
  try {
    await cliApi.post('/admin/bootstrap', {
      workspaceName: answers.workspaceName,
      adminEmail: answers.adminEmail,
      adminPassword: answers.adminPassword,
    });
    console.log(chalk.green(`\nAdmin user created: ${answers.adminEmail}`));
  } catch {
    console.log(chalk.yellow(
      '\nCould not create admin user (server not running?).',
    ));
    console.log(chalk.dim(
      'Start the server, then register via the Web UI at http://localhost:3000 — the first user becomes admin.',
    ));
  }

  console.log(chalk.bold.green('\nSetup complete.\n'));
}
