import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { cliApi } from '../api.js';

interface InitAnswers {
  workspaceName: string;
  adminEmail: string;
  adminPassword: string;
  confirmPassword: string;
  generateEncryptionKey: boolean;
  dataDir: string;
}

/**
 * First-time setup wizard for HonorClaw.
 *
 * - Generates encryption keys
 * - Creates the admin user
 * - Writes the configuration file
 */
export async function runInit(): Promise<void> {
  console.log(chalk.bold('\nHonorClaw Setup Wizard\n'));

  // Check if already initialized
  const configPath = path.resolve('honorclaw.yaml');
  if (fs.existsSync(configPath)) {
    const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([
      {
        type: 'confirm',
        name: 'overwrite',
        message: 'honorclaw.yaml already exists. Overwrite?',
        default: false,
      },
    ]);
    if (!overwrite) {
      console.log(chalk.dim('Aborted.'));
      return;
    }
  }

  // Gather inputs
  const answers = await inquirer.prompt<InitAnswers>([
    {
      type: 'input',
      name: 'workspaceName',
      message: 'Workspace name:',
      default: 'default',
      validate: (v: string) => v.trim().length > 0 || 'Workspace name is required',
    },
    {
      type: 'input',
      name: 'adminEmail',
      message: 'Admin email:',
      validate: (v: string) => v.includes('@') || 'Enter a valid email address',
    },
    {
      type: 'password',
      name: 'adminPassword',
      message: 'Admin password:',
      mask: '*',
      validate: (v: string) => v.length >= 12 || 'Password must be at least 12 characters',
    },
    {
      type: 'password',
      name: 'confirmPassword',
      message: 'Confirm password:',
      mask: '*',
      validate: (v: string, a?: InitAnswers) =>
        v === a?.adminPassword || 'Passwords do not match',
    },
    {
      type: 'confirm',
      name: 'generateEncryptionKey',
      message: 'Generate a new encryption key?',
      default: true,
    },
    {
      type: 'input',
      name: 'dataDir',
      message: 'Data directory:',
      default: '/data/honorclaw',
    },
  ]);

  // ── Generate encryption key ─────────────────────────────────────────
  let encryptionKey: string;
  if (answers.generateEncryptionKey) {
    encryptionKey = crypto.randomBytes(32).toString('hex');
    console.log(chalk.green('\nEncryption key generated.'));
    console.log(chalk.dim('Store this securely — it cannot be recovered:\n'));
    console.log(`  ${chalk.yellow(encryptionKey)}\n`);
  } else {
    const { key } = await inquirer.prompt<{ key: string }>([
      {
        type: 'password',
        name: 'key',
        message: 'Encryption key (64 hex chars):',
        mask: '*',
        validate: (v: string) =>
          /^[0-9a-f]{64}$/i.test(v) || 'Must be a 64-character hex string',
      },
    ]);
    encryptionKey = key;
  }

  // ── Generate session cookie secret ──────────────────────────────────
  const cookieSecret = crypto.randomBytes(32).toString('base64url');

  // ── Generate JWT signing key ────────────────────────────────────────
  const jwtSecret = crypto.randomBytes(48).toString('base64url');

  // ── Write config file ───────────────────────────────────────────────
  const config = [
    '# HonorClaw Configuration',
    '# Generated by `honorclaw init`',
    '',
    'server:',
    '  port: 3000',
    '  host: "0.0.0.0"',
    '  corsOrigins:',
    '    - "http://localhost:3000"',
    `  sessionCookieSecret: "${cookieSecret}"`,
    '',
    'database:',
    '  name: honorclaw',
    '  poolSize: 10',
    '',
    'redis: {}',
    '',
    'auth:',
    '  jwtIssuer: honorclaw',
    '  accessTokenTtlMinutes: 60',
    '  refreshTokenTtlDays: 7',
    '  mfaRequired: false',
    '',
    'llm:',
    '  defaultModel: "ollama/llama3.2"',
    '  providers: {}',
    '',
    'embeddings:',
    '  provider: ollama',
    '  model: nomic-embed-text',
    '',
    'security:',
    '  mode: namespace',
    '',
    'storage:',
    '  type: local',
    `  root: "${answers.dataDir}"`,
    '',
    'tools:',
    '  timeoutSeconds: 30',
    '  registries:',
    '    - type: local',
    '',
  ].join('\n');

  fs.writeFileSync(configPath, config, 'utf-8');
  console.log(chalk.green(`Configuration written to ${configPath}`));

  // ── Store secrets in .env file (gitignored) ─────────────────────────
  const envPath = path.resolve('.env');
  const envContent = [
    '# HonorClaw secrets — DO NOT COMMIT',
    `HONORCLAW_ENCRYPTION_KEY=${encryptionKey}`,
    `HONORCLAW_JWT_SECRET=${jwtSecret}`,
    `HONORCLAW_COOKIE_SECRET=${cookieSecret}`,
    '',
  ].join('\n');

  fs.writeFileSync(envPath, envContent, { mode: 0o600 });
  console.log(chalk.green(`Secrets written to ${envPath}`));

  // ── Create admin user via API (if server is running) ────────────────
  try {
    await cliApi.post('/admin/bootstrap', {
      workspaceName: answers.workspaceName,
      adminEmail: answers.adminEmail,
      adminPassword: answers.adminPassword,
    });
    console.log(chalk.green(`\nAdmin user created: ${answers.adminEmail}`));
  } catch {
    console.log(chalk.yellow(
      '\nCould not create admin user (server not running?).',
    ));
    console.log(chalk.dim(
      'Start the server and run `honorclaw init --admin-only` to create the admin user.',
    ));
  }

  console.log(chalk.bold.green('\nSetup complete.\n'));
}
